### ISSUE TITLE
runExport FAILED

### ISSUE THREAD

**Issue by Algogator** [FutureCitiesCatapult/TomboloDigitalConnector#490] opened 2018-02-20 03:36 UTC
### Versions

Please provide your platform details:

| Software | Information |
| :--- | :--- |
| Operating System| `Ubuntu` |
| OS Version| `16.04` |
| java -version | `1.8.0_161` | 
| psql --version | `10.2` |
| gradle --version | `4.5` |

### Description

I tried to run 

`gradle runExport   -Precipe='src/main/resources/executions/examples/london-cycle-traffic-air-quality-lsoa-backoff.json'   -Poutput='~/Desktop/london-cycle-traffic-air-quality-lsoa-backoff-output.json'`

but it fails with 

### Error log

```
> Task :runExport FAILED
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2018-02-19 21:30:16.316 [main] WARN  n.s.e.config.ConfigurationFactory - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/home/anna/.gradle/caches/modules-2/files-2.1/net.sf.ehcache/ehcache/2.10.3/cf74f9a4a049f181833b147a1d9aa62159c9d01d/ehcache-2.10.3.jar!/ehcache-failsafe.xml
2018-02-19 21:30:16.965 [main] INFO  uk.org.tombolo.AbstractRunner - Setting file download cache: /tmp
2018-02-19 21:30:17.045 [main] INFO  org.ehcache.core.EhcacheManager - Cache 'fields' created in EhcacheManager.
2018-02-19 21:30:17.046 [main] ERROR uk.org.tombolo.AbstractRunner - Error initialising output writer: ~/Desktop/london-cycle-traffic-air-quality-lsoa-backoff-output.json


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runExport'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1

```

**Comment by lorenaqendro** [comment] 2018-02-20 08:36
Thank you for creating the issue. I believe the problem is in how the home directory is specified: try replacing `~/Desktop` with `/home/$USER/Desktop` and replace `$USER` with your user name.

I will change it in the documentation too.

**Comment by lorenaqendro** [comment] 2018-04-11 10:10
Closing as not an issue anymore.

**Closed by lorenaqendro** 2018-04-11 10:10 UTC
